application/application/views/stocks_main/main.py
from flask import request, Blueprint,render_template,jsonify
from werkzeug.exceptions import BadRequest, InternalServerError
import application.misc.stocks_getter

stocks_main_views = Blueprint("stocks_main_views",
                       __name__,
                       url_prefix="/stocks"
                       )

@stocks_main_views.route("/indexes/", methods=["GET"],endpoint='indexes')
def indexes_dynamics():
    return render_template('indexes.html')


@stocks_main_views.route("/add_stock/", methods=["GET","POST"],endpoint='add_stock')
def add_stock():

    return render_template('indexes.html')


#endpoint='get_index_price
#https://www.tutorialsteacher.com/jquery/jquery-ajax-method
@stocks_main_views.route("/get_index_price/", methods=["GET"])
def get_today_price_url():
    ticker = request.args.get('ticker')
    price = application.misc.stocks_getter.get_today_price(ticker)
    return jsonify(
        ticker=ticker,
        price=price
    )
    # return jsonify(result=price)
@stocks_main_views.route("/get_indexes_prices/", methods=["GET"])
def get_today_price_several_url():
    # tickers = request.args.get('several_tickers')
    tickers = request.args.getlist("several_tickers")
    # print('==============',tickers)
    # print('==============',statuses)
    prices = application.misc.stocks_getter.get_today_prices_several(tickers)
    return jsonify(prices)

application/templates/add_stock.html
{% extends 'base.html' %}

{% block title %}
    add stock page
{% endblock %}


{% block body %}
    <h1> Indexes page</h1>
<script>
const response = await fetch('/plot')
const item = await response.json()
Bokeh.embed.embed_item(item)
</script>
{% endblock %}

application/templates/base.html
<!doctype html>
<html lang="en">
<title>
    {% block title %}
    Default title


    {% endblock %}
</title>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <title>Dashboard Template · Bootstrap v5.0</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/dashboard/">


    <!-- Bootstrap core CSS -->
    <!--<link href="css/bootstrap.min.css" rel="stylesheet">-->
    <link rel="stylesheet" href="{{ url_for('static',filename='css/bootstrap.min.css') }}">
    <script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"></script>
    {% block head %}
    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>
    {% endblock %}

    <!-- Custom styles for this template -->
    <!--    <link href="dashboard.css" rel="stylesheet">-->
    <link rel="stylesheet" href="{{ url_for('static',filename='scr/dashboard.css') }}">
</head>





<header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
    <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="#">Anexander V project</a>
    <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse"
            data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false"
            aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
        <h1 class="text-warning text-lg-end " >Hello {{ username }}</h1>
    <div class="navbar-nav">
        <div class="nav-item text-nowrap">
            <a class="nav-link px-3" href="{{ url_for('logout') }}">Sign out</a>
        </div>
    </div>
</header>

<body>
#}

<div class="container-fluid">
    <div class="row">
        <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
            <div class="position-sticky pt-3">
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{{ url_for('index') }}">
                            <span data-feather="home"></span>
                            Main indexes today's dynamics
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('stocks_main_app.index_stocks') }}">
                            <span data-feather="file"></span>
                            Indexes dynamics
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('stocks_main_views.add_stock') }}">
                            <span data-feather="shopping-cart"></span>
                            Crypto dynamics
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <span data-feather="bar-chart-2"></span>
                            News
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <span data-feather="layers"></span>
                            Integrations
                        </a>
                    </li>
                </ul>

{#                <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">#}
{#                    <span>Saved reports</span>#}
{#                    <a class="link-secondary" href="#" aria-label="Add a new report">#}
{#                        <span data-feather="plus-circle"></span>#}
{#                    </a>#}
{#                </h6>#}
{#                <ul class="nav flex-column mb-2">#}
{#                    <li class="nav-item">#}
{#                        <a class="nav-link" href="#">#}
{#                            <span data-feather="file-text"></span>#}
{#                            Current month#}
{#                        </a>#}
{#                    </li>#}
{#                    <li class="nav-item">#}
{#                        <a class="nav-link" href="#">#}
{#                            <span data-feather="file-text"></span>#}
{#                            Last quarter#}
{#                        </a>#}
{#                    </li>#}
{#                    <li class="nav-item">#}
{#                        <a class="nav-link" href="#">#}
{#                            <span data-feather="file-text"></span>#}
{#                            Social engagement#}
{#                        </a>#}
{#                    </li>#}
{#                    <li class="nav-item">#}
{#                        <a class="nav-link" href="#">#}
{#                            <span data-feather="file-text"></span>#}
{#                            Year-end sale#}
{#                        </a>#}
{#                    </li>#}
{#                </ul>#}
            </div>
        </nav>

{#        <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">#}
{#            <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">#}
{#            <br>#}
{#                <h1 class="h2">Dashboard</h1>#}
{#                <div class="btn-toolbar mb-2 mb-md-0">#}
{#                    <div class="btn-group me-2">#}
{#                        <button type="button" class="btn btn-sm btn-outline-secondary">Share</button>#}
{#                        <button type="button" class="btn btn-sm btn-outline-secondary">Export</button>#}
{#                    </div>#}
{#                    <button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle">#}
{#                        <span data-feather="calendar"></span>#}
{#                        This week#}
{#                    </button>#}
{#                </div>#}
{#            </div>#}

{#            <canvas class="my-4 w-100" id="myChart" width="900" height="380"></canvas>#}
            {% block body %}
            {% endblock %}
            {%  block body2 %}

            {% endblock %}
        </main>
    </div>
</div>



<script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"></script>

<script src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js"
        integrity="sha384-uO3SXW5IuS1ZpFPKugNNWqTZRRglnUJK6UAZ/gxOX80nxEkN9NcGZTftn6RzhGWE"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js"
        integrity="sha384-zNy6FEbO50N+Cg5wap8IKA4M/ZnLJgzc6w2NqACZaK0u0FXfOWRRJOnQtpZun8ha"
        crossorigin="anonymous"></script>
{#<script src="{{ url_for('static', filename='scr/dashboard.js') }}"></script>#}
{#<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>#}
{#<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>#}
<script src="{{ url_for('static', filename='js/jquery-3.6.0.min.js') }}"></script>
{#<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>#}

<script src="{{ url_for('static', filename='js/bokeh-2.3.3.min.js') }}"></script>
</body>

</html>

application/templates/indexes.html
{% extends 'base.html' %}

{% block title %}
    Index page
{% endblock %}

{% block body %}

{% endblock %}

application/templates/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
</head>

<body>
<h1> Here is something</h1>
<div id="myplot" class="p-3 mb-2 bg-secondary text-white">.bg-secondary >
<script>
fetch('/plot')
    .then(function(response) { return response.json() })
    .then(function(item) { return Bokeh.embed.embed_item(item) })
</script>
</div>
<script src="{{ url_for('static', filename='js/bokeh-2.3.3.min.js') }}"></script>

</body>
</html>